
package com.edenorte.turnos.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140803.1500
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WsConsultasICODENService", targetNamespace = "http://webservice.webicoden.edenorte.com/", wsdlLocation = "http://ensprlinux:8001/WsConsultasICODENService/WsConsultasICODEN?wsdl")
public class WsConsultasICODENService
    extends Service
{

    private final static URL WSCONSULTASICODENSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSCONSULTASICODENSERVICE_EXCEPTION;
    private final static QName WSCONSULTASICODENSERVICE_QNAME = new QName("http://webservice.webicoden.edenorte.com/", "WsConsultasICODENService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ensprlinux:8001/WsConsultasICODENService/WsConsultasICODEN?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCONSULTASICODENSERVICE_WSDL_LOCATION = url;
        WSCONSULTASICODENSERVICE_EXCEPTION = e;
    }

    public WsConsultasICODENService() {
        super(__getWsdlLocation(), WSCONSULTASICODENSERVICE_QNAME);
    }

    public WsConsultasICODENService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCONSULTASICODENSERVICE_QNAME, features);
    }

    public WsConsultasICODENService(URL wsdlLocation) {
        super(wsdlLocation, WSCONSULTASICODENSERVICE_QNAME);
    }

    public WsConsultasICODENService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCONSULTASICODENSERVICE_QNAME, features);
    }

    public WsConsultasICODENService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsConsultasICODENService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsConsultasICODEN
     */
    @WebEndpoint(name = "WsConsultasICODENPort")
    public WsConsultasICODEN getWsConsultasICODENPort() {
        return super.getPort(new QName("http://webservice.webicoden.edenorte.com/", "WsConsultasICODENPort"), WsConsultasICODEN.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsConsultasICODEN
     */
    @WebEndpoint(name = "WsConsultasICODENPort")
    public WsConsultasICODEN getWsConsultasICODENPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.webicoden.edenorte.com/", "WsConsultasICODENPort"), WsConsultasICODEN.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCONSULTASICODENSERVICE_EXCEPTION!= null) {
            throw WSCONSULTASICODENSERVICE_EXCEPTION;
        }
        return WSCONSULTASICODENSERVICE_WSDL_LOCATION;
    }

}
