
package com.edenorte.turnos.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140803.1500
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WsConsultasICODEN", targetNamespace = "http://webservice.webicoden.edenorte.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsConsultasICODEN {


    /**
     * 
     * @param nic
     * @return
     *     returns com.edenorte.turnos.ws.IncidenciasResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getIncidencias", targetNamespace = "http://webservice.webicoden.edenorte.com/", className = "com.edenorte.turnos.ws.GetIncidencias")
    @ResponseWrapper(localName = "getIncidenciasResponse", targetNamespace = "http://webservice.webicoden.edenorte.com/", className = "com.edenorte.turnos.ws.GetIncidenciasResponse")
    @Action(input = "http://webservice.webicoden.edenorte.com/WsConsultasICODEN/getIncidenciasRequest", output = "http://webservice.webicoden.edenorte.com/WsConsultasICODEN/getIncidenciasResponse")
    public IncidenciasResponse getIncidencias(
        @WebParam(name = "NIC", targetNamespace = "")
        Integer nic);

    /**
     * 
     * @param nic
     * @return
     *     returns com.edenorte.turnos.ws.OrdenesServicioResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrdenesServicio", targetNamespace = "http://webservice.webicoden.edenorte.com/", className = "com.edenorte.turnos.ws.GetOrdenesServicio")
    @ResponseWrapper(localName = "getOrdenesServicioResponse", targetNamespace = "http://webservice.webicoden.edenorte.com/", className = "com.edenorte.turnos.ws.GetOrdenesServicioResponse")
    @Action(input = "http://webservice.webicoden.edenorte.com/WsConsultasICODEN/getOrdenesServicioRequest", output = "http://webservice.webicoden.edenorte.com/WsConsultasICODEN/getOrdenesServicioResponse")
    public OrdenesServicioResponse getOrdenesServicio(
        @WebParam(name = "NIC", targetNamespace = "")
        Integer nic);

    /**
     * 
     * @param nic
     * @return
     *     returns com.edenorte.turnos.ws.ReclamacionesResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReclamaciones", targetNamespace = "http://webservice.webicoden.edenorte.com/", className = "com.edenorte.turnos.ws.GetReclamaciones")
    @ResponseWrapper(localName = "getReclamacionesResponse", targetNamespace = "http://webservice.webicoden.edenorte.com/", className = "com.edenorte.turnos.ws.GetReclamacionesResponse")
    @Action(input = "http://webservice.webicoden.edenorte.com/WsConsultasICODEN/getReclamacionesRequest", output = "http://webservice.webicoden.edenorte.com/WsConsultasICODEN/getReclamacionesResponse")
    public ReclamacionesResponse getReclamaciones(
        @WebParam(name = "NIC", targetNamespace = "")
        Integer nic);

    /**
     * 
     * @param nic
     * @return
     *     returns com.edenorte.turnos.ws.DatosCliente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDatosCliente", targetNamespace = "http://webservice.webicoden.edenorte.com/", className = "com.edenorte.turnos.ws.GetDatosCliente")
    @ResponseWrapper(localName = "getDatosClienteResponse", targetNamespace = "http://webservice.webicoden.edenorte.com/", className = "com.edenorte.turnos.ws.GetDatosClienteResponse")
    @Action(input = "http://webservice.webicoden.edenorte.com/WsConsultasICODEN/getDatosClienteRequest", output = "http://webservice.webicoden.edenorte.com/WsConsultasICODEN/getDatosClienteResponse")
    public DatosCliente getDatosCliente(
        @WebParam(name = "NIC", targetNamespace = "")
        Integer nic);

}
